project_id                  = "your-test-project-id"
quota_project_id            = "your-test-project-id"
region                      = "us-central1"
firestore_database_name     = "(default)"
cloud_run_service_name      = "mona-proctor-backend"
firebase_web_app_display_name = "mona-proctor-web"
artifact_repository_name    = "mona-proctor"
cloud_run_container_image   = "us-central1-docker.pkg.dev/your-test-project-id/mona-proctor/backend:wave11"
